# Generated by Django 5.0.7 on 2024-07-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['-date_joined'], 'verbose_name_plural': 'Employers'},
        ),
        migrations.AddField(
            model_name='employer',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
