# Generated by Django 5.0.7 on 2024-12-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='artisan',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='service',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
