# Generated by Django 5.0.7 on 2024-07-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_alter_employer_options_employer_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='company_website',
        ),
        migrations.AddField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
