# Generated by Django 5.0.7 on 2024-08-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_remove_employer_company_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'JobPosts'},
        ),
    ]
