# Generated by Django 5.0.7 on 2024-08-18 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0015_artisan_pay_alter_artisan_industry'),
        ('employers', '0004_alter_jobpost_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('job_date', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_order', to='artisans.artisan')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
