# Generated by Django 5.0.7 on 2024-08-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_orderdetails_orderrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequest',
            name='artisan',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='employer',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.DeleteModel(
            name='OrderRequest',
        ),
    ]
