# Generated by Django 5.0.7 on 2024-11-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='artisan',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='service',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
