# Generated by Django 5.0.7 on 2024-07-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='img',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='noimge', upload_to='service_images/'),
        ),
    ]
