# Generated by Django 5.0.7 on 2024-08-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_service_image_service_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
