# Generated by Django 5.0.7 on 2024-08-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_service_icon_alter_service_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the industry', max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
