# Generated by Django 5.0.7 on 2024-12-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0002_remove_artisanprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
