# Generated by Django 5.0.7 on 2024-12-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0003_artisanprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
