# Generated by Django 5.0.7 on 2024-12-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0004_alter_artisanprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='nin',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
