# Generated by Django 5.0.7 on 2024-12-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0005_alter_artisanprofile_nin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerprofile',
            name='location',
        ),
    ]
