# Generated by Django 5.0.7 on 2024-12-14 06:32

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0006_remove_managerprofile_location'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.area'),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='fingerprint_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
