# Generated by Django 5.0.7 on 2024-12-28 09:57

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0008_remove_artisanprofile_fingerprint_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('fingerprint_template', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='acct.artisanprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
