# Generated by Django 5.0.7 on 2025-01-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0009_fingerprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerprint',
            name='fingerprint_template',
        ),
    ]
