# Generated by Django 5.0.7 on 2025-03-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0011_marketerprofile_artisanprofile_marketer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanprofile',
            name='marketer',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employer', 'Employer'), ('artisan', 'Artisan'), ('marketer', 'Marketer')], max_length=10),
        ),
    ]
