# Generated by Django 5.0.7 on 2025-03-11 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0012_remove_artisanprofile_marketer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='marketer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_artisans', to='acct.marketerprofile'),
        ),
    ]
