# Generated by Django 5.0.7 on 2025-03-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0013_artisanprofile_marketer'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='profile_image_resized',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/resized/'),
        ),
    ]
