# Generated by Django 5.0.7 on 2025-03-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0014_artisanprofile_profile_image_resized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanprofile',
            name='profile_image_resized',
        ),
    ]
