# Generated by Django 5.0.7 on 2025-04-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0015_remove_artisanprofile_profile_image_resized'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
