# Generated by Django 5.0.7 on 2025-05-19 14:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0017_calculate_commissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketerprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
