# Generated by Django 5.0.7 on 2025-05-19 14:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0018_marketerprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
