# Generated by Django 5.0.7 on 2024-07-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_artisan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
    ]
