# Generated by Django 5.0.7 on 2024-12-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_remove_jobdetails_added_at_remove_jobdetails_artisan'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='artisan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
