# Generated by Django 5.0.7 on 2024-12-29 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0009_fingerprint'),
        ('employer', '0004_jobdetails_artisan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acct.employerprofile'),
        ),
    ]
