# Generated by Django 5.0.7 on 2025-02-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_paymentinformation_delete_paymentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinformation',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='paymentinformation',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='paymentinformation',
            name='customer_phone',
        ),
    ]
