# Generated by Django 5.0.7 on 2025-02-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0014_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
