# Generated by Django 5.0.7 on 2025-02-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0016_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
