# Generated by Django 5.0.7 on 2025-02-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0017_alter_transaction_tx_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
