# Generated by Django 5.0.7 on 2025-02-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0018_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentInformation',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
