# Generated by Django 5.0.7 on 2025-02-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0020_transactiondetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiondetails',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
