# Generated by Django 5.0.7 on 2025-02-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0021_rename_amount_transactiondetails_total_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionDetails',
        ),
    ]
