# Generated by Django 5.0.7 on 2025-02-18 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0027_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
