# Generated by Django 5.0.7 on 2025-03-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0031_alter_cartitem_cart_alter_transactiondetails_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetails',
            name='cart',
        ),
    ]
