# Generated by Django 5.0.7 on 2025-03-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0032_remove_transactiondetails_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='cart',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
