# Generated by Django 5.0.7 on 2025-03-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0034_alter_transactiondetails_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='flutter_app_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
