# Generated by Django 5.0.7 on 2025-07-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0036_alter_order_total_price_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='expectedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In_Progress'), ('completed', 'Completed')], max_length=20),
        ),
    ]
