# Generated by Django 5.0.7 on 2025-02-26 01:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('company_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('date_joined', models.DateField(auto_now_add=True, null=True)),
                ('contact', models.CharField(max_length=255)),
            ],
        ),
    ]
