# Generated by Django 5.0.7 on 2024-07-19 13:06

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=3)),
                ('location', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Area',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin', models.CharField(max_length=11, unique=True)),
                ('experience', models.IntegerField(help_text='Experience in years')),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=15, null=True, unique=True)),
                ('years_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_img', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateField(auto_now_add=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artisans.area')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisan_profile', to='accounts.user')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisans', to='artisans.profession')),
            ],
        ),
    ]
