# Generated by Django 5.0.7 on 2024-12-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='location',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='nin',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='service',
        ),
    ]
