# Generated by Django 5.0.7 on 2024-12-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_remove_artisan_experience_remove_artisan_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
