# Generated by Django 5.0.7 on 2024-12-09 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_remove_artisan_experience_remove_artisan_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='Artisan',
        ),
    ]
