# Generated by Django 5.0.7 on 2024-07-22 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0004_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
