# Generated by Django 5.0.7 on 2024-07-26 06:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0005_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='profile_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
