# Generated by Django 5.0.7 on 2024-07-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0007_alter_artisan_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
