# Generated by Django 5.0.7 on 2024-07-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0008_alter_artisan_address_alter_artisan_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artisan',
            options={'ordering': ['-date_joined'], 'verbose_name_plural': 'Employers'},
        ),
    ]
