# Generated by Django 5.0.7 on 2024-08-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0009_alter_artisan_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='artisan',
            options={'ordering': ['-date_joined'], 'verbose_name_plural': 'Artisans'},
        ),
        migrations.AddField(
            model_name='artisan',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artisans', to='artisans.service'),
        ),
    ]
