# Generated by Django 5.0.7 on 2024-08-01 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0010_service_alter_artisan_options_artisan_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artisans', to='artisans.profession'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
