# Generated by Django 5.0.7 on 2024-08-01 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0011_alter_artisan_service_delete_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='profession',
        ),
    ]
