# Generated by Django 5.0.7 on 2024-08-02 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_service_icon_alter_service_location_and_more'),
        ('artisans', '0012_remove_artisan_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artisans', to='api.service'),
        ),
    ]
